services:
  reservations:
    build:
      context: .
      dockerfile: apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/reservations/.env
    environment:
      - CI=true
    depends_on:
      - mysql

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/auth/.env
    environment:
      - CI=true
    depends_on:
      - mysql

  payments:
    build:
      context: .
      dockerfile: apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    env_file:
      - ./apps/payments/.env  
    environment:
      - CI=true
    depends_on:
      - mysql   

  notifications:
    build:
      context: .
      dockerfile: apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    env_file:
      - ./apps/notifications/.env  
    environment:
      - CI=true
    depends_on:
      - mysql     

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes: 
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: