apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments
  name: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - image: 923605793720.dkr.ecr.us-east-1.amazonaws.com/payments:latest
          imagePullPolicy: Always
          name: payments
          env:
            - name: PORT
              value: '3003'
            - name: NOTIFICATIONS_HOST
              value: "notifications"
            - name: NOTIFICATIONS_PORT
              value: '3004'
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: stripeSecretKey
          ports:
            - containerPort: 3003
