apiVersion: v1
kind: Service
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: reservations
